services:
  portainer_agent:
    image: portainer/agent:2.19.4
    container_name: portainer_agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001

  dashboard:
    image: helblingjoel/piserver:20240706
    container_name: dashboard
    ports:
      - "80:3000"
    restart: unless-stopped
    volumes:
      - /mnt/hdd/sqlite/timesheet.sqlite3:/app/timesheet.sqlite3
      - /mnt/hdd/sqlite/energyBills.sqlite3:/app/energyBills.sqlite3
    environment:
      DATABASE_URL: "no_longer_needed"
      OCTOPUS_ACCOUNT_NUMBER: "A-1D7C8FF7"
      TZ: "Europe/London"
      OCTOPUS_API_KEY: "sk_live"
      OCTOPUS_ELECTRIC_MPAN: ""
      OCTOPUS_ELECTRIC_SERIAL: ""
      OCTOPUS_GAS_MPRN: ""
      OCTOPUS_GAS_SERIAL: ""
      MOVE_IN_DATE: "2000-10-01"
      ADDRESS_CODE: ""

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/hdd/filebrowser/files/media/jellyfin-config:/config
      - /mnt/hdd/filebrowser/files/media/tvshows:/tvshows:ro
      - /mnt/hdd/filebrowser/files/media/movies:/movies:ro
      - /mnt/hdd/filebrowser/files/media/music:/music:ro
      - /mnt/hdd/filebrowser/files/media/videos:/videos:ro
      - jellyfin_cache:/cache
    ports:
      - 8096:8096

  nr-agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    environment:
      NRIA_LICENSE_KEY: eu...

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - /mnt/hdd/filebrowser/files:/srv
      - /mnt/hdd/filebrowser/config/filebrowser.db:/database.db
      - /mnt/hdd/filebrowser/config/branding:/config/branding
      - /mnt/hdd/filebrowser/config/settings.json:/filebrowser.json
    environment:
      FB_BASEURL: "/files"

volumes:
  portainer_data:
  pihole-data:
  pihole-dns:
  plexappstate:
  jellyfin_cache: