services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "81:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Europe/London"
    volumes:
      - "pihole-data:/etc/pihole/"
      - "pihole-dns:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  castblock:
    image: erdnaxeli/castblock
    container_name: castblock
    network_mode: host
    restart: unless-stopped
    environment:
      - MUTE_ADS=true

volumes:
  portainer_data:
  pihole-data:
  pihole-dns: