name: Build image
on:
 pull_request:
  branches:
   - main
jobs:
 build:
  runs-on: ubuntu-latest
  if: github.event_name == 'pull_request'
  steps:
   - name: Checkout repo
     uses: actions/checkout@v3
     with:
      fetch-depth: 0
      ref: ${{ github.head_ref }}

   - name: Login to DockerHub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
   - name: Set current date as env variable
     run: echo "::set-output name=date::$(date +'%Y%m%d')"
     id: date

   - name: Set up QEMU
     uses: docker/setup-qemu-action@v2

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v2

   - name: Build and push
     uses: docker/build-push-action@v4
     with:
      context: .
      file: ./Dockerfile
      push: false
      platforms: linux/arm/v8
      tags: helblingjoel/piserver:PR${{ github.event.pull_request.number }}
      cache-from: type=gha
      cache-to: type=gha,mode=max

 test:
  runs-on: ubuntu-latest
  if: github.event_name == 'pull_request'
  steps:
   - name: Checkout repo
     uses: actions/checkout@v3
     with:
      fetch-depth: 0
      ref: ${{ github.head_ref }}

   - name: Install Node.js
     uses: actions/setup-node@v2
     with:
      node-version: "18"

   - name: Install dependencies
     run: npm install

   - name: Run tests
     run: npm run test
