name: CD
on:
 push:
  branches:
   - main
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repo
     uses: actions/checkout@v3
     with:
      fetch-depth: 0
      ref: ${{ github.head_ref }}
   - name: Install Node
     uses: actions/setup-node@v2
     with:
      node-version: "18"

   - name: Install dependencies
     run: npm install
   - name: Run unit tests
     run: npm run test

 audit:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repo
     uses: actions/checkout@v3
     with:
      fetch-depth: 0
      ref: ${{ github.head_ref }}

   - name: Install Node.js
     uses: actions/setup-node@v2
     with:
      node-version: "18"

   - name: Run tests
     run: npm audit

 docker:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    runner:
     - arm64v8
  steps:
   - uses: actions/checkout@v2
   - name: Extract branch name
     shell: bash
     run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
     id: extract_branch

   - name: Checkout repo
     uses: actions/checkout@v2
     with:
      fetch-depth: 0
      ref: ${{ steps.extract_branch.outputs.branch }}

   - name: Login to DockerHub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Set current date as env variable
     run: echo "::set-output name=date::$(date +'%Y%m%d')"
     id: date
   - name: Set up QEMU
     uses: docker/setup-qemu-action@v2
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1

   - name: Build and push
     uses: docker/build-push-action@v2
     with:
      context: .
      file: ./Dockerfile
      push: true
      platforms: linux/arm/v8
      tags: helblingjoel/piserver:${{ steps.date.outputs.date }}
      cache-from: type=gha
      cache-to: type=gha,mode=max

 restart:
  needs: docker
  name: Redeploy
  runs-on: strawberry
  steps:
   - name: Login to DockerHub
     uses: docker/login-action@v1
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
   - name: Set current date as env variable
     run: echo "::set-output name=date::$(date +'%Y%m%d')"
     id: date
   - name: Stop running container
     run: docker stop dashboard || true && docker rm dashboard || true
   - name: Remove existing image
     run: docker image rm helblingjoel/piserver:${{steps.date.outputs.date }} ||
      true
   - name: Start container
     run: docker run -p 80:3000 -d --name dashboard --restart unless-stopped -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -e OCTOPUS_ACCOUNT_NUMBER=${{ secrets.OCTOPUS_ACCOUNT_NUMBER}} -e TZ=Europe/London -e OCTOPUS_BASE_URL=https://api.octopus.energy/v1 -e OCTOPUS_API_KEY=${{ secrets.OCTOPUS_API_KEY }} -e OCTOPUS_ELECTRIC_MPAN=${{ secrets.OCTOPUS_ELECTRIC_MPAN }} -e OCTOPUS_ELECTRIC_SERIAL=${{ secrets.OCTOPUS_ELECTRIC_SERIAL }} -e OCTOPUS_GAS_MPRN=${{ secrets.OCTOPUS_GAS_MPRN }} -e OCTOPUS_GAS_SERIAL=${{ secrets.OCTOPUS_GAS_SERIAL }} -e MOVE_IN_DATE=${{ secrets.MOVE_IN_DATE }} -e ADDRESS_CODE=${{ secrets.ADDRESS_CODE }} helblingjoel/piserver:${{  steps.date.outputs.date }}
